DROP TABLE IF EXISTS comments, bookings, items, requests, users CASCADE;

-- таблица пользователей
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- таблица запросов на вещь
CREATE TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        description VARCHAR(512) NOT NULL,
                                        requestor_id BIGINT NOT NULL,
                                        created TIMESTAMP NOT NULL,
                                        CONSTRAINT pk_requests PRIMARY KEY (id),
                                        CONSTRAINT fk_requests_to_user FOREIGN KEY (requestor_id) REFERENCES users(id)
);

-- таблица вещей
CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(256) NOT NULL,
                                     description VARCHAR(256) NOT NULL,
                                     owner_id BIGINT NOT NULL,
                                     available BOOLEAN NOT NULL,
                                     last_booking TIMESTAMP,
                                     next_booking TIMESTAMP,
                                     request_id BIGINT,
                                     CONSTRAINT pk_item PRIMARY KEY (id),
                                     CONSTRAINT fk_items_owner FOREIGN KEY (owner_id) REFERENCES users(id),
                                     CONSTRAINT fk_items_request FOREIGN KEY (request_id) REFERENCES requests(id)
);

-- таблица бронирования вещей
CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        start_date TIMESTAMP NOT NULL,
                                        end_date TIMESTAMP NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        booker_id BIGINT NOT NULL,
                                        status VARCHAR(8) NOT NULL,
                                        CONSTRAINT pk_booking PRIMARY KEY (id),
                                        CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(id),
                                        CONSTRAINT fk_booking_user FOREIGN KEY (booker_id) REFERENCES users(id)
);

-- таблица отзывов
CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        author_id BIGINT NOT NULL,
                                        text VARCHAR(512) NOT NULL,
                                        created TIMESTAMP NOT NULL,
                                        CONSTRAINT pk_comments PRIMARY KEY (id),
                                        CONSTRAINT fk_comments_to_item FOREIGN KEY (item_id) REFERENCES items(id),
                                        CONSTRAINT fk_comments_to_user FOREIGN KEY (author_id) REFERENCES users(id)
);


